In [18]:
import pandas as pd
import pymongo
from pandas.io.json import json_normalize

In [3]:
from pymongo import MongoClient 
client = MongoClient("mongodb://admin:admin@localhost:32768")
db = client.mybbdd

In [4]:
docs = db.docs.find({"founded_year":{"$gte":2010}})
print(len(list(docs)))

146

In [5]:
# 1. All the companies that it's name match 'Babelgum'. Retrieve only their name field.
companies1 = db.docs.find({"name":{"$eq":"Babelgum"}}, { "name": 1 , "_id": 0})
companies1[0]

{'name': 'Babelgum'}

In [7]:
# 2. All the companies that have more than 5000 employees. Limit the search to 20 companies and sort them by number of employees.
companies2 = db.docs.find({"number_of_employees":{"$gte":500}}, limit=20, projection={ "name": 1 , "number_of_employees": 1, "_id": 0}).sort("number_of_employees", pymongo.DESCENDING)
companies2 = pd.DataFrame(list(companies2))
companies2

                                          name  number_of_employees
0                                      Siemens               405000
1                                          IBM               388000
2                                       Toyota               320000
3                                       PayPal               300000
4   Nippon Telegraph and Telephone Corporation               227000
5                          Samsung Electronics               221726
6                                    Accenture               205000
7                    Tata Consultancy Services               200300
8                    Flextronics International               200000
9                                      Safeway               186000
10                                        Sony               180500
11                                          LG               177000
12                                        Ford               171000
13                                      Boeing               160000
14               Digital Equipment Corporation               140000
15                                       Nokia               125000
16                         MItsubishi Electric               107000
17                         MItsubishi Electric               107000
18                                     Comcast               100000
19                                 Bertelsmann               100000

In [8]:
# 3. All the companies founded between 2000 and 2005, both years included. Retrieve only the name and founded_yearfileds.
companies3 = db.docs.find({'founded_year':{'$gte':2000, '$lte':2005}}, projection={'name':1, 'founded_year':1, '_id':0})
companies3 = pd.DataFrame(list(companies3))
companies3

      founded_year                     name
0             2005                 Wetpaint
1             2005                     Zoho
2             2004                     Digg
3             2005                Omnidrive
4             2003                   Gizmoz
5             2002              StumbleUpon
6             2005                    Helio
7             2004                 Facebook
8             2002                    Plaxo
9             2004                  AddThis
10            2002               Technorati
11            2004                     Veoh
12            2005          Jingle Networks
13            2002                   Meetup
14            2005                   Wesabe
15            2002                  SmugMug
16            2005                Jangl SMS
17            2005                 LifeLock
18            2005                    Jajah
19            2005                  YouTube
20            2003                    Skype
21            2004           Pando Networks
22            2003                     Ikan
23            2002                    Topix
24            2003                delicious
25            2004                 AllPeers
26            2004                  Jobster
27            2005                Revision3
28            2000                 AllofMP3
29            2005                   iSkoot
...            ...                      ...
3704          2000             LogicLibrary
3705          2002       AGEIA Technologies
3706          2001             SOA Software
3707          2003                 WV Fiber
3708          2003                 SheKnows
3709          2004                  LeadRev
3710          2004                 MediaPal
3711          2004   LED Grow Master Global
3712          2001                   Edgeos
3713          2004          findownersearch
3714          2002                  Prolify
3715          2004                Fotothing
3716          2000                  Vigilos
3717          2004               OptiMedica
3718          2001             CScout Japan
3719          2002    AffittiVacanze-Spagna
3720          2005     Mu-Gahat Enterprises
3721          2004                 ITERNOVA
3722          2002          Luminus Devices
3723          2004               AwardSpace
3724          2000             Block Shield
3725          2000                  Netrake
3726          2004                 NextLabs
3727          2001           Cameron Health
3728          2004  Celestial Semiconductor
3729          2003                  Intergy
3730          2004           Axon Solutions
3731          2000           EnterSys Group
3732          2002               AfterLogic
3733          2000                EnteGreat

[3734 rows x 2 columns]

In [25]:
#4. All the companies that had a Valuation Amount of more than 100.000.000 and have been founded before 2010. Retrieve only the name and ipo fields.
companies4 = db.docs.find({'$and': [{'ipo.valuation_amount': {'$gt':100000000}}, {'founded_year': {'$lt':2010}}]}, projection={'name':1, 'ipo':1, '_id':0})
companies4 = json_normalize(list(companies4))
companies4

,ipo.pub_day,ipo.pub_month,ipo.pub_year,ipo.stock_symbol,ipo.valuation_amount,ipo.valuation_currency_code,name
0,18.0,5.0,2012.0,NASDAQ:FB,104000000000,USD,Facebook
1,7.0,11.0,2013.0,NYSE:TWTR,18100000000,USD,Twitter
2,2.0,3.0,2012.0,NYSE:YELP,1300000000,USD,Yelp
3,20.0,7.0,2011.0,NYSE:LNKD,9310000000,USD,LinkedIn
4,17.0,2.0,2012.0,NASDAQ:BCOV,290000000,USD,Brightcove
5,NaN,5.0,1997.0,NASDAQ:AMZN,100000000000,USD,Amazon
6,27.0,7.0,2010.0,KITD,235000000,USD,KIT digital
7,26.0,1.0,2011.0,NYSE:NLSN,1600000000,USD,Nielsen
8,21.0,5.0,2009.0,NASDAQ:OPEN,1050000000,USD,OpenTable
9,23.0,5.0,2013.0,NYSE:ECOM,287000000,USD,ChannelAdvisor
10,3.0,2.0,2012.0,NASDAQ:JIVE,1000000000,USD,Jive Software
11,19.0,7.0,2011.0,NASDAQ:Z,2550000000,USD,Zillow
12,6.0,11.0,2013.0,NASDAQ:WIX,750000000,USD,Wix
13,29.0,9.0,2006.0,SFLY,350000000,USD,Shutterfly
14,21.0,12.0,2011.0,TRIP,3273770000,USD,TripAdvisor
15,2.0,7.0,2004.0,NYSE:CRM,110000000,USD,Salesforce
16,29.0,6.0,2011.0,NASDAQ:AWAY,3000000000,USD,HomeAway
17,11.0,1.0,2010.0,NASDAQ:QNST,140000000,USD,QuinStreet
18,7.0,11.0,2011.0,RAX,5440000000,USD,Rackspace
19,12.0,8.0,1988.0,NASDAQ:BMC,6000000000,USD,BMC Software
20,NaN,NaN,NaN,NYSE:ONE,1060000000,USD,Higher One
21,20.0,4.0,2012.0,NYSE:BLOX,824000000,USD,Infoblox
22,16.0,6.0,2004.0,HK:0700,11000000000,USD,Tencent
23,2.0,4.0,2013.0,NASDAQ:MKTO,465000000,USD,Marketo
24,5.0,8.0,2005.0,NASDAQ:BIDU,4000000000,USD,Baidu
25,2.0,11.0,2010.0,GKNT,134000000,USD,Geeknet
26,9.0,3.0,2001.0,NASDAQ:LDCL,450000000,USD,Opsware
27,13.0,5.0,2010.0,TNAV,337000000,USD,Telenav
28,12.0,4.0,2013.0,RALY,315000000,USD,Rally Software
29,22.0,4.0,2011.0,NASDAQ:BRSE,1000000000,USD,BrightSource Energy
30,14.0,9.0,2006.0,JP:2121,970000000,USD,Mixi
31,16.0,7.0,2010.0,QLIK,1000000000,USD,QlikTech
32,14.0,11.0,2013.0,NYSE:CHGG,1100000000,USD,Chegg
33,14.0,11.0,2013.0,NYSE:CHGG,1100000000,USD,Chegg
34,7.0,11.0,2011.0,NASDAQ:GRPN,12800000000,USD,Groupon
35,20.0,5.0,2009.0,SWI,803000000,USD,SolarWinds
36,17.0,12.0,2008.0,3632,108960000000,JPY,GREE
37,NaN,NaN,NaN,NASDAQ:TUDO,174000000,USD,Tudou
38,14.0,2.0,2011.0,NASDAQ:DMAN,245000000,USD,DemandTec
39,5.0,7.0,2011.0,CSOD,900000000,USD,Cornerstone OnDemand
40,NaN,NaN,NaN,NYSE:WDC,9430000000,USD,Western Digital
41,28.0,3.0,2012.0,NYSE:MM,973500000,USD,Millennial Media

In [10]:
# 5. All the companies that have less than 1000 employees and have been founded before 2005. Order them by the number of employees and limit the search to 10 companies.
companies5 = db.docs.find({'$and':[{"number_of_employees":{"$lt":1000}},{'founded_year':{'$lt':2005}}]}, limit=10, projection={'name':1, 'founded_year':1, 'number_of_employees':1}).sort('number_of_employees', pymongo.DESCENDING)
companies5 = pd.DataFrame(list(companies5))
companies5

,_id,founded_year,name,number_of_employees
0,52cdef7d4bab8bd675298933,2000,Infinera Corporation,974
1,52cdef7e4bab8bd67529ac95,1997,NorthPoint Communications Group,948
2,52cdef7f4bab8bd67529be17,1997,888 Holdings,931
3,52cdef7c4bab8bd6752986a2,1983,Forrester Research,903
4,52cdef7e4bab8bd67529af6d,1991,SonicWALL,900
5,52cdef7e4bab8bd67529b21b,1999,Webmetrics,900
6,52cdef7e4bab8bd67529b3bd,1999,Cornerstone OnDemand,881
7,52cdef7c4bab8bd675297de0,2004,Yelp,800
8,52cdef7c4bab8bd675297efd,2000,ZoomInfo,800
9,52cdef7c4bab8bd675297ef5,2003,MySpace,800

In [11]:
# 6. All the companies that don't include the partners field.
companies6 = db.docs.find({'partners':{'$eq':[]}}, limit=200, projection={'name':1, 'partners':1})
companies6 = pd.DataFrame(list(companies6))
companies6

                          _id                   name partners
0    52cdef7c4bab8bd675297d8b              AdventNet       []
1    52cdef7c4bab8bd675297d8a               Wetpaint       []
2    52cdef7c4bab8bd675297d8c                   Zoho       []
3    52cdef7c4bab8bd675297d8d                   Digg       []
4    52cdef7c4bab8bd675297d8f              Omnidrive       []
5    52cdef7c4bab8bd675297d92                Flektor       []
6    52cdef7c4bab8bd675297d91                   Geni       []
7    52cdef7c4bab8bd675297d93  Fox Interactive Media       []
8    52cdef7c4bab8bd675297d90                Postini       []
9    52cdef7c4bab8bd675297d96                 Gizmoz       []
10   52cdef7c4bab8bd675297d95            StumbleUpon       []
11   52cdef7c4bab8bd675297d97                 Scribd       []
12   52cdef7c4bab8bd675297d99                   Lala       []
13   52cdef7c4bab8bd675297d98                Slacker       []
14   52cdef7c4bab8bd675297d9a                  Helio       []
15   52cdef7c4bab8bd675297d9c                MeetMoi       []
16   52cdef7c4bab8bd675297d8e               Facebook       []
17   52cdef7c4bab8bd675297d9d                  Joost       []
18   52cdef7c4bab8bd675297d9e                    CBS       []
19   52cdef7c4bab8bd675297d9f                 Viacom       []
20   52cdef7c4bab8bd675297da0               Babelgum       []
21   52cdef7c4bab8bd675297d9b                   eBay       []
22   52cdef7c4bab8bd675297da1                  Plaxo       []
23   52cdef7c4bab8bd675297d94                Twitter       []
24   52cdef7c4bab8bd675297da4               Powerset       []
25   52cdef7c4bab8bd675297da6                SpinVox       []
26   52cdef7c4bab8bd675297da7                AddThis       []
27   52cdef7c4bab8bd675297da5             Technorati       []
28   52cdef7c4bab8bd675297da9                 Mahalo       []
29   52cdef7c4bab8bd675297daa                Sparter       []
..                        ...                    ...      ...
170  52cdef7c4bab8bd675297e34                  Piczo       []
171  52cdef7c4bab8bd675297e37                Cyworld       []
172  52cdef7c4bab8bd675297e2e             stylediary       []
173  52cdef7c4bab8bd675297e38               PhotoBox       []
174  52cdef7c4bab8bd675297e3b             Socialtext       []
175  52cdef7c4bab8bd675297e3d              IceRocket       []
176  52cdef7c4bab8bd675297e3f                barablu       []
177  52cdef7c4bab8bd675297e3a            Spreadshirt       []
178  52cdef7c4bab8bd675297e3e                 spigit       []
179  52cdef7c4bab8bd675297e3c            Bazaarvoice       []
180  52cdef7c4bab8bd675297e41      ConnectMeAnywhere       []
181  52cdef7c4bab8bd675297e43                  Ohloh       []
182  52cdef7c4bab8bd675297e40           PowerReviews       []
183  52cdef7c4bab8bd675297e45               Clipperz       []
184  52cdef7c4bab8bd675297e42              LiveWorld       []
185  52cdef7c4bab8bd675297e44                    hi5       []
186  52cdef7c4bab8bd675297e46                 Tagged       []
187  52cdef7c4bab8bd675297e49               Nintendo       []
188  52cdef7c4bab8bd675297e47              ScanScout       []
189  52cdef7c4bab8bd675297e4c                 Cerado       []
190  52cdef7c4bab8bd675297e4a                 Indeed       []
191  52cdef7c4bab8bd675297e4b                  Jaxtr       []
192  52cdef7c4bab8bd675297e4e                ONEsite       []
193  52cdef7c4bab8bd675297e4d               NetSuite       []
194  52cdef7c4bab8bd675297e50                  Kwiqq       []
195  52cdef7c4bab8bd675297e48              37signals       []
196  52cdef7c4bab8bd675297e4f          introNetworks       []
197  52cdef7c4bab8bd675297e52                WikiYou       []
198  52cdef7c4bab8bd675297e51                  Going       []
199  52cdef7c4bab8bd675297e53               Wallhogs       []

[200 rows x 3 columns]

In [12]:
#7. All the companies that have a null type of value on the category_code field.
companies7 = db.docs.find({'category_code':{'$type':['null']}}, limit=200, projection={'name':1, 'category_code':1, '_id':0})
companies7 = pd.DataFrame(list(companies7))
companies7

    category_code                   name
0            None             Collective
1            None                Snimmer
2            None                 KoolIM
3            None           Level9 Media
4            None                VidKing
5            None                  Drigg
6            None              SpaceTime
7            None          Touch Clarity
8            None                 MMDAYS
9            None           Inside Group
10           None         Repeater Store
11           None                 Tapesh
12           None              iPersians
13           None              NewPersia
14           None              Pyra Labs
15           None                Feedmap
16           None              NuvoMedia
17           None                Intwine
18           None  The Weinstein Company
19           None               ExecuNet
20           None            A1Vacations
21           None              TripHomes
22           None           Picturehouse
23           None  Covalent Technologies
24           None               Telepost
25           None               Fidelity
26           None                  Quirk
27           None              Epic Trip
28           None             Leechblock
29           None                Skyrove
..            ...                    ...
170          None              Starbucks
171          None           Housenetwork
172          None          New Media Age
173          None        British Telecom
174          None           Nichenet Pty
175          None         MyDataIsMyData
176          None                 geoURL
177          None               ASPextra
178          None               365 Main
179          None              ThePlanet
180          None              Visioneer
181          None              livesteez
182          None          E-mail Vision
183          None                   GF-X
184          None         Netconversions
185          None                   BMAT
186          None                Froogle
187          None                IceChat
188          None                   mIRC
189          None          Vendare Media
190          None           Pulse Mobile
191          None                  Logix
192          None            Radioactive
193          None               RoRCraft
194          None        AllYouCanUpload
195          None          Message Media
196          None                Sxipper
197          None    Quote Desk Software
198          None            Upgradebase
199          None             Quickbooks

[200 rows x 2 columns]

In [23]:
# 8. All the companies that have at least 100 employees but less than 1000. Retrieve only the name and number of employees fields.
companies8 = db.docs.find({'number_of_employees':{'$gte': 100, '$lt': 1000}}, projection={'name':1, 'number_of_employees':1})
companies8 = pd.DataFrame(list(companies8))
companies8

,_id,name,number_of_employees
0,52cdef7c4bab8bd675297d8b,AdventNet,600
1,52cdef7c4bab8bd675297da7,AddThis,120
2,52cdef7c4bab8bd675297da8,OpenX,305
3,52cdef7c4bab8bd675297db5,LifeLock,644
4,52cdef7c4bab8bd675297dbb,Jajah,110
5,52cdef7c4bab8bd675297dc0,Livestream,120
6,52cdef7c4bab8bd675297dc1,Ustream,250
7,52cdef7c4bab8bd675297dda,iContact,300
8,52cdef7c4bab8bd675297de0,Yelp,800
9,52cdef7c4bab8bd675297dee,Dailymotion,120
10,52cdef7c4bab8bd675297df0,RockYou,106
11,52cdef7c4bab8bd675297e09,Meebo,200
12,52cdef7c4bab8bd675297e0a,Eventbrite,200
13,52cdef7c4bab8bd675297e10,Box,950
14,52cdef7c4bab8bd675297e15,Conduit,215
15,52cdef7c4bab8bd675297e19,Redfin,100
16,52cdef7c4bab8bd675297e26,oDesk,120
17,52cdef7c4bab8bd675297e27,Simply Hired,100
18,52cdef7c4bab8bd675297e38,PhotoBox,600
19,52cdef7c4bab8bd675297e3a,Spreadshirt,230
20,52cdef7c4bab8bd675297e3e,spigit,120
21,52cdef7c4bab8bd675297e3c,Bazaarvoice,600
22,52cdef7c4bab8bd675297e40,PowerReviews,120
23,52cdef7c4bab8bd675297e44,hi5,100
24,52cdef7c4bab8bd675297e46,Tagged,162
25,52cdef7c4bab8bd675297e6d,PayScale,130
26,52cdef7c4bab8bd675297e72,Truphone,450
27,52cdef7c4bab8bd675297e81,Brightcove,220
28,52cdef7c4bab8bd675297e82,Hightail,200
29,52cdef7c4bab8bd675297e83,Nimbuzz,140
...,...,...,...
887,52cdef7f4bab8bd67529c49e,Enliven Marketing Technologies,146
888,52cdef7f4bab8bd67529c4d4,Avira,500
889,52cdef7f4bab8bd67529c4da,800APP,200
890,52cdef7f4bab8bd67529c505,Optium,267
891,52cdef7f4bab8bd67529c50c,Wondershare Software,350
892,52cdef7f4bab8bd67529c55d,Amber Networks,223
893,52cdef7f4bab8bd67529c56a,NetScaler,180
894,52cdef7f4bab8bd67529c56c,OSA Technologies,102
895,52cdef7f4bab8bd67529c57c,Abilis Solutions,160
896,52cdef7f4bab8bd67529c588,Applied Language Solutions,100
897,52cdef7f4bab8bd67529c599,Catapult Communications,205
898,52cdef7f4bab8bd67529c5ba,iomart Group,260
899,52cdef7f4bab8bd67529c5d6,Swiftprosys,180
900,52cdef7f4bab8bd67529c5e9,G5 Entertainment,107
901,52cdef7f4bab8bd67529c5fe,InfoLogix,206
902,52cdef7f4bab8bd67529c603,TGS Geophysicl,696
903,52cdef7f4bab8bd67529c601,smartFOCUS,550
904,52cdef7f4bab8bd67529c609,INX,433
905,52cdef7f4bab8bd67529c616,Ambassadors Group,267
906,52cdef7f4bab8bd67529c618,optionsXpress,305
907,52cdef7f4bab8bd67529c61e,Embarcadero Technologies,450
908,52cdef7f4bab8bd67529c649,AuthenTec,220
909,52cdef7f4bab8bd67529c65c,SheKnows,200
910,52cdef7f4bab8bd67529c6ac,Inventa Technologies,207
911,52cdef7f4bab8bd67529c6a2,Savvion,160
912,52cdef7f4bab8bd67529c6d1,UOL (Universo Online),500
913,52cdef7f4bab8bd67529c6d8,NextLabs,100
914,52cdef7f4bab8bd67529c6e6,OfficialVirtualDJ,102
915,52cdef7f4bab8bd67529c6f1,Willdan Group,385
916,52cdef7f4bab8bd67529c6f3,QSGI,164

In [20]:
# 9. Order all the companies by their IPO price descendently.
companies9 = db.docs.find({'ipo.valuation_amount':{'$type':'number'}}, projection={"name":1 ,"ipo.valuation_amount": 1}).sort("ipo.valuation_amount", pymongo.DESCENDING)
companies9 = json_normalize(list(companies9))
companies9

                         _id  ipo.valuation_amount                        name
0   52cdef7e4bab8bd67529a8b4          108960000000                        GREE
1   52cdef7c4bab8bd675297d8e          104000000000                    Facebook
2   52cdef7c4bab8bd675297e7a          100000000000                      Amazon
3   52cdef7c4bab8bd675297d94           18100000000                     Twitter
4   52cdef7d4bab8bd675299d5d           12800000000                     Groupon
5   52cdef7c4bab8bd675298674           11000000000                     Tencent
6   52cdef7e4bab8bd67529b996            9430000000             Western Digital
7   52cdef7c4bab8bd675297e0c            9310000000                    LinkedIn
8   52cdef7c4bab8bd67529859a            6000000000                BMC Software
9   52cdef7c4bab8bd675298527            5440000000                   Rackspace
10  52cdef7c4bab8bd675298760            4000000000                       Baidu
11  52cdef7c4bab8bd6752981a7            3273770000                 TripAdvisor
12  52cdef7c4bab8bd6752982f6            3000000000                    HomeAway
13  52cdef7c4bab8bd67529800c            2550000000                      Zillow
14  52cdef7c4bab8bd675297f15            1600000000                     Nielsen
15  52cdef7c4bab8bd675297de0            1300000000                        Yelp
16  52cdef7d4bab8bd67529984e            1100000000                       Chegg
17  52cdef7d4bab8bd675299bd8            1100000000                       Chegg
18  52cdef7e4bab8bd67529a415            1096000000             RPX Corporation
19  52cdef7c4bab8bd675298649            1060000000                  Higher One
20  52cdef7c4bab8bd675297f36            1050000000                   OpenTable
21  52cdef7c4bab8bd675297f95            1000000000               Jive Software
22  52cdef7d4bab8bd675298d12            1000000000         BrightSource Energy
23  52cdef7d4bab8bd6752992c1            1000000000                    QlikTech
24  52cdef7e4bab8bd67529bb87             973500000            Millennial Media
25  52cdef7d4bab8bd675299103             970000000                        Mixi
26  52cdef7e4bab8bd67529b3bd             900000000        Cornerstone OnDemand
27  52cdef7c4bab8bd67529865c             824000000                    Infoblox
28  52cdef7e4bab8bd67529a7db             803000000                  SolarWinds
29  52cdef7c4bab8bd67529805d             750000000                         Wix
..                       ...                   ...                         ...
31  52cdef7d4bab8bd6752989a0             450000000                     Opsware
32  52cdef7f4bab8bd67529c456             367350000                      Emdeon
33  52cdef7c4bab8bd675298112             350000000                  Shutterfly
34  52cdef7d4bab8bd6752989f2             337000000                     Telenav
35  52cdef7d4bab8bd675298d0e             315000000              Rally Software
36  52cdef7f4bab8bd67529c266             300000000                         STR
37  52cdef7c4bab8bd675297e81             290000000                  Brightcove
38  52cdef7c4bab8bd675297f42             287000000              ChannelAdvisor
39  52cdef7f4bab8bd67529c633             275000000                Elster Group
40  52cdef7e4bab8bd67529ad05             245000000                   DemandTec
41  52cdef7c4bab8bd675297ee5             235000000                 KIT digital
42  52cdef7e4bab8bd67529aae7             174000000                       Tudou
43  52cdef7c4bab8bd6752983da             160000000                        DivX
44  52cdef7c4bab8bd6752984e3             140000000                  QuinStreet
45  52cdef7c4bab8bd6752987fe             134000000                     Geeknet
46  52cdef7c4bab8bd67529823b             110000000                  Salesforce
47  52cdef7c4bab8bd675297efb             100000000                      JumpTV
48  52cdef7f4bab8bd67529c057              95500000                     EnerNOC
49  52cdef7e4bab8bd67529aa42              66600000               Meru Networks
50  52cdef7f4bab8bd67529bf8d              55000000            Real Goods Solar
51  52cdef7f4bab8bd67529c2fa              50000000                Global Water
52  52cdef7d4bab8bd675299576              44000000                     Pironet
53  52cdef7d4bab8bd675299900              44000000                     Pironet
54  52cdef7d4bab8bd67529980b              30000000                       Inuvo
55  52cdef7d4bab8bd675299b95              30000000                       Inuvo
56  52cdef7f4bab8bd67529c4d6              25000000  Energy and Power Solutions
57  52cdef7c4bab8bd67529809f              11003200                      Vringo
58  52cdef7f4bab8bd67529bf8e               5000000                    GT Solar
59  52cdef7d4bab8bd67529959e                117900                        DeNA
60  52cdef7d4bab8bd675299928                117900                        DeNA

[61 rows x 3 columns]

In [22]:
# 10. Retrieve the 10 companies with more employees, order by the number of employees
companies10 = db.docs.find({'number_of_employees':{'$gte': 0}}, limit=10, projection={'name':1, 'number_of_employees':1}).sort('number_of_employees', pymongo.DESCENDING)
companies10 = pd.DataFrame(list(companies10))
companies10

,_id,name,number_of_employees
0,52cdef7d4bab8bd67529941a,Siemens,405000
1,52cdef7c4bab8bd67529856a,IBM,388000
2,52cdef7d4bab8bd675299d33,Toyota,320000
3,52cdef7c4bab8bd675297e89,PayPal,300000
4,52cdef7e4bab8bd67529b0fe,Nippon Telegraph and Telephone Corporation,227000
5,52cdef7d4bab8bd675298aa4,Samsung Electronics,221726
6,52cdef7d4bab8bd675298b99,Accenture,205000
7,52cdef7e4bab8bd67529a657,Tata Consultancy Services,200300
8,52cdef7e4bab8bd67529aa51,Flextronics International,200000
9,52cdef7d4bab8bd675299156,Safeway,186000

In [24]:
# 11. All the companies founded on the second semester of the year. Limit your search to 1000 companies.
companies11 = db.docs.find({'founded_month':{'$gte': 6}}, limit=100, projection={'name':1, 'founded_month':1})
companies11 = json_normalize(list(companies11))
companies11

                         _id  founded_month                   name
0   52cdef7c4bab8bd675297d8a             10               Wetpaint
1   52cdef7c4bab8bd675297d8c              9                   Zoho
2   52cdef7c4bab8bd675297d8d             10                   Digg
3   52cdef7c4bab8bd675297d8f             11              Omnidrive
4   52cdef7c4bab8bd675297d91              6                   Geni
5   52cdef7c4bab8bd675297d93              6  Fox Interactive Media
6   52cdef7c4bab8bd675297d90              6                Postini
7   52cdef7c4bab8bd675297d9d             10                  Joost
8   52cdef7c4bab8bd675297d9b              9                   eBay
9   52cdef7c4bab8bd675297da1             11                  Plaxo
10  52cdef7c4bab8bd675297da4             10               Powerset
11  52cdef7c4bab8bd675297da5              6             Technorati
12  52cdef7c4bab8bd675297daa              6                Sparter
13  52cdef7c4bab8bd675297dab             12                   Kyte
14  52cdef7c4bab8bd675297dae             12                  Thoof
15  52cdef7c4bab8bd675297daf              9        Jingle Networks
16  52cdef7c4bab8bd675297db6             12                 Wesabe
17  52cdef7c4bab8bd675297db8             11                SmugMug
18  52cdef7c4bab8bd675297db5              8               LifeLock
19  52cdef7c4bab8bd675297dbc              8                  Skype
20  52cdef7c4bab8bd675297dc3              7         Pando Networks
21  52cdef7c4bab8bd675297dc6             12                   Ikan
22  52cdef7c4bab8bd675297dba              9                 Google
23  52cdef7c4bab8bd675297dc8              6                  Topix
24  52cdef7c4bab8bd675297dc7              9              delicious
25  52cdef7c4bab8bd675297dcc              8               AllPeers
26  52cdef7c4bab8bd675297dd0              8                   Wize
27  52cdef7c4bab8bd675297dd5              6               AllofMP3
28  52cdef7c4bab8bd675297dd7              8              SellABand
29  52cdef7c4bab8bd675297ddb              7                 MeeVee
..                       ...            ...                    ...
70  52cdef7c4bab8bd675297e3e              6                 spigit
71  52cdef7c4bab8bd675297e41              9      ConnectMeAnywhere
72  52cdef7c4bab8bd675297e45             11               Clipperz
73  52cdef7c4bab8bd675297e44             12                    hi5
74  52cdef7c4bab8bd675297e46             10                 Tagged
75  52cdef7c4bab8bd675297e49              9               Nintendo
76  52cdef7c4bab8bd675297e4c              7                 Cerado
77  52cdef7c4bab8bd675297e4a             11                 Indeed
78  52cdef7c4bab8bd675297e4b             10                  Jaxtr
79  52cdef7c4bab8bd675297e4e              9                ONEsite
80  52cdef7c4bab8bd675297e53              8               Wallhogs
81  52cdef7c4bab8bd675297e54              6            Respectance
82  52cdef7c4bab8bd675297e58              9                 eBuddy
83  52cdef7c4bab8bd675297e5a             12                Grockit
84  52cdef7c4bab8bd675297e62              7                JumpBox
85  52cdef7c4bab8bd675297e63             11               Phonezoo
86  52cdef7c4bab8bd675297e65              7            Relationals
87  52cdef7c4bab8bd675297e64              7               LongJump
88  52cdef7c4bab8bd675297e66             11                Wishpot
89  52cdef7c4bab8bd675297e71              8                 Forbes
90  52cdef7c4bab8bd675297e73              7                 Boonex
91  52cdef7c4bab8bd675297e5d             12          Adobe Systems
92  52cdef7c4bab8bd675297e78              7                 Rebtel
93  52cdef7c4bab8bd675297e75             12          IntenseDebate
94  52cdef7c4bab8bd675297e7e              7                boo-box
95  52cdef7c4bab8bd675297e7d              7                 Buxfer
96  52cdef7c4bab8bd675297e85             12              TextPayMe
97  52cdef7c4bab8bd675297e88              9               BillMonk
98  52cdef7c4bab8bd675297e8c              6                 MeeMix
99  52cdef7c4bab8bd675297e8f              6             Alstrasoft

[100 rows x 3 columns]

In [26]:
# 12. All the companies that have been 'deadpooled' after the third year.

In [27]:
# 13. All the companies founded before 2000 that have and acquisition amount of more than 10.000.000
companies13 = db.docs.find({'$and' : [{"founded_year":{'$lt':2000}}, {"acquisition.price_amount":{'$gt':10000000}}]},projection={"name": 1 , "founded_year": 1, "acquisition.price_amount": 1})
companies13 = json_normalize(list(companies13))
companies13

,_id,acquisition.price_amount,founded_year,name
0,52cdef7c4bab8bd675297d90,625000000,1999,Postini
1,52cdef7c4bab8bd675297deb,180000000,1999,SideStep
2,52cdef7c4bab8bd675297e2c,25000000,1999,Recipezaar
3,52cdef7c4bab8bd675297e89,1500000000,1998,PayPal
4,52cdef7c4bab8bd675297e97,300000000,1999,Snapfish
5,52cdef7c4bab8bd675297eaa,160000000,1999,Neopets
6,52cdef7c4bab8bd675297ee9,7400000000,1982,Sun Microsystems
7,52cdef7c4bab8bd675297efe,1200000000,1999,Zappos
8,52cdef7c4bab8bd675297f0c,1000000000,1999,Alibaba
9,52cdef7c4bab8bd675297f28,4300000000,1960,Sabre
10,52cdef7c4bab8bd675297f29,1008000000,1998,Lastminute
11,52cdef7c4bab8bd675297f32,64000000,1994,Sportsline
12,52cdef7c4bab8bd675297f34,71000000,1995,Webshots
13,52cdef7c4bab8bd675297f33,1300000000,1980,Digitas
14,52cdef7c4bab8bd675297f3a,11600000,1999,MIVA
15,52cdef7c4bab8bd675297f5b,600000000,1995,iVillage
16,52cdef7c4bab8bd675297f65,485000000,1999,PriceGrabber
17,52cdef7c4bab8bd675297fca,425000000,1996,LinkShare
18,52cdef7c4bab8bd675297fcc,18400000,1999,Kaboose
19,52cdef7c4bab8bd675297fce,132000000,1998,Fastclick
20,52cdef7c4bab8bd675298048,871000000,1999,Eloqua
21,52cdef7c4bab8bd6752980d0,1800000000,1996,Omniture
22,52cdef7c4bab8bd6752980d3,775000000,1995,Interwoven
23,52cdef7c4bab8bd6752980dc,250000000,1999,HowStuffWorks
24,52cdef7c4bab8bd6752980e0,100000000,1994,RealAge
25,52cdef7c4bab8bd67529816b,50000000,1995,Match
26,52cdef7c4bab8bd67529821d,30000000,1999,Xdrive
27,52cdef7c4bab8bd675298223,250000000,1996,Alexa
28,52cdef7c4bab8bd67529827f,91400000,1996,ioko
29,52cdef7c4bab8bd675298278,65000000,1996,Offermatica
...,...,...,...,...
175,52cdef7f4bab8bd67529c403,24820000,1998,Digital Forest
176,52cdef7f4bab8bd67529c405,13450000,1993,Connect3 Systems
177,52cdef7f4bab8bd67529c44e,105000000,1979,Tidal Software
178,52cdef7f4bab8bd67529c492,53000000,1999,AppStream
179,52cdef7f4bab8bd67529c49e,71000000,1987,Enliven Marketing Technologies
180,52cdef7f4bab8bd67529c4a6,87110000,1991,Integration Associates
181,52cdef7f4bab8bd67529c4a0,73300000,1990,NetManage
182,52cdef7f4bab8bd67529c4d3,830000000,1985,Sophos
183,52cdef7f4bab8bd67529c507,249000000,1990,HireRight
184,52cdef7f4bab8bd67529c50a,290000000,1986,Photon Dynamics
185,52cdef7f4bab8bd67529c50b,300000000,1993,NetCracker Technology
186,52cdef7f4bab8bd67529c514,471390000,1999,NuTech Solutions
187,52cdef7f4bab8bd67529c519,720000000,1968,Metrologic Instruments
188,52cdef7f4bab8bd67529c53c,180000000,1986,Sierra Monolithics
189,52cdef7f4bab8bd67529c555,30000000,1945,Veeco Instruments
190,52cdef7f4bab8bd67529c564,552000000,1998,Lightera
191,52cdef7f4bab8bd67529c56a,300000000,1997,NetScaler
192,52cdef7f4bab8bd67529c599,106140000,1985,Catapult Communications
193,52cdef7f4bab8bd67529c5d4,10500000,1997,Easyspace
194,52cdef7f4bab8bd67529c611,15000000,1999,Iron Solutions
195,52cdef7f4bab8bd67529c615,18000000,1999,Bookrags
196,52cdef7f4bab8bd67529c621,28000000,1981,Aleri Global Banking
197,52cdef7f4bab8bd67529c623,29350000,1989,Muniservices
198,52cdef7f4bab8bd67529c649,356000000,1998,AuthenTec
199,52cdef7f4bab8bd67529c672,1400000000,1969,Vertafore
200,52cdef7f4bab8bd67529c6ac,30000000,1993,Inventa Technologies
201,52cdef7f4bab8bd67529c6a2,49000000,1994,Savvion
202,52cdef7f4bab8bd67529c6bb,23200000,1998,Universal Microwave
203,52cdef7f4bab8bd67529c6c3,18780000,1982,Advanced Control Components
204,52cdef7f4bab8bd67529c6f2,15040000,1974,Contemporary Computer Services

In [37]:
# 14. All the companies that have been acquired after 2015, order by the acquisition amount, and retrieve only their nameand acquisiton field.
companies14 = db.docs.find({[{"acquisition.acquired_year":{'$lt':2015}}]},projection={"name": 1, "acquisition.acquired_year": 1, '_id':0}).sort("acquisition.price_amount", pymongo.DESCENDING)
#companies14 = pd.DataFrame(list(companies14))
companies14

TypeError: unhashable type: 'list'